name: android-apk
on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: android-actions/setup-android@v3
      - name: Install Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;27.1.12297006"
          yes | sdkmanager --licenses
      - name: Install NPM deps
        working-directory: FPVDroneGame
        run: npm ci --legacy-peer-deps
      - name: Gradle perms
        working-directory: FPVDroneGame/android
        run: chmod +x ./gradlew
      - name: Build release
        working-directory: FPVDroneGame/android
        run: ./gradlew assembleRelease --no-daemon --stacktrace
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
      - name: Find APK
        id: apk
        run: echo "path=$(find FPVDroneGame/android/app/build/outputs/apk/release -name '*.apk' -print -quit)" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ steps.apk.outputs.path }}
      - name: Attach to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.apk.outputs.path }}